---
output: 
  html_fragment
fontsize: 12pt
---

# Project Description
As part of the final project for my EPI 563 (Concepts and Applications in Spatial Epidemiology) class, my partner and I chose to focus on WASH related issues. One of the Millennium Development Goals (2000-2015) was to halve the population without access to improved water sources by 2015. While this goal was met, a newer Sustainable Development Goal aims for everyone to have access to safely managed drinking water (improved water source). Among areas of the world, the African continent has the lowest access to improved water sources. This project aims to describe the spatial patterns in access to improved water sources in Africa using publicly available 2011-2020 data from the Demagraphic and Health Surveys Program.

***

# Skills & Methods Utilized

* R scripting
* Global Moran's I
* Moran's I on Model's Residuals
* LISA
* Mapping using tmap
* Reproducibility with renv
<div align='right'>
  <p>Project GitHub<br>
  <a href="https://github.com/akalangara/AfricaDHSWASH">
    <i class="fa fa-github" style='font-size:20px; margin: 0px 5px'></i>
  </a>
</div>

***

# Deliverable

